# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Ubuntu C++ Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Install dependencies
            run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++ pkg-config

          - name: Install ffmpeg
            run: sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev libswscale-dev

          - name: Configure with CMake
            run: cmake -B build -S . -G Ninja

          - name: Build
            run: cmake --build build
